spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saritaksharma/springboot-redis-session-authentication.git

      
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8888
